# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: glash_development
  host: localhost
  pool: 5
  username: pg
  password: pg
  min_messages: warning
test: &test
  adapter: postgresql
  encoding: unicode
  database: gtest
  host: localhost
  pool: 5
  username: postgres
  password: postgres
  min_messages: warning


production:
  adapter: postgresql
  encoding: unicode
  database: glash_production
  host: localhost
  pool: 5
  username: <%= ENV['PROD_DATABASE_USERNAME'] %>
  password: <%= ENV['PROD_DATABASE_PASSWORD'] %>
  min_messages: warning

cucumber:
  <<: *test
